env:
  global:
    - PROJECT_NAME=bkt-mobiliario
    # master SHA256-606c78f9bd55e946b34762b7f54b65177eaa37a3fc42559ea62712cf30431b2b
    - secure: ""
    # beta SHA256-
    - secure: "H/Q4zBvAlgj3vala9FaGdgpSIqAHO2dOTgCounCPuOL+YlTxssrFEGHbk2tskvWJofjJzYGupZPGYU0fa4e3NYpfmcMKiMMzv7rOu/YFGlJiJrXH5xK6WJcnpmKpG8wg89uM1v0b1+M/Hs/N6pguqj/OI+1XXq83/Dr2khufkCnLFjQPwrmi3Mzfl7Z/EdyQVbVv8vhp5NxvL2zgNdh0zK95NJWvVPXATgMSzlXwpnoUO5adkC2t+3R1m9wGawSUd1qhYL15iC0ARoOaY6z5KITPdEz2g2SVaGOlr/J3ItGQ4NFqVyLgUQ4UHONMQ1+axvn+pNvS9cEQ75GX4y3wQ4PSuHQu4TLfe70h3nIZgo/lcFqXx39X+HDwP08D6alGmhSGeR3fFerm48kgT1D+uxdZA+bkCV1aUgBU/XjJMgbyQsNkgDEKjX3u++AbjlgmsaYWpauWCFbEWD1Zrs13Mm30cI+RTTEm0ZLfcXs4G50iNlgKjtvw3vEZoFnhEuYuU5DWT1tiWws7XU01N1POrF97fGPLb2w+xvnJEst+wAFRWAcNKWQf23J6INsfd5K1UveMXNikS5azBQTOdX/hatykpzPBuSe9oYoz2eF4sxAZpTyMOuKlXuqIB0bzkj3yQ+WBDvkA52DbbeGq6G3F5tsYSJ+q7UMMumB9ChUbjAk="
script:
  - true
notifications:
  email: false
  slack: krrrunch:Heq9HQZoEZT9rZJohu8in30e
language: node_js
node_js:
  - "6"
before_deploy:
  - 'git config --global user.email "deploy@travis-ci"'
  - 'git config --global user.name "[Deploy]"'
  - export GIT_FTP_URL_BRANCH=GIT_FTP_URL_$TRAVIS_BRANCH
  - './git-ftp add-scope $TRAVIS_BRANCH "${!GIT_FTP_URL_BRANCH}"'
  - git config git-ftp.syncroot public
  - npm install -g uglify-js
  - gem install sass -v 3.4.23 --no-ri --no-rdoc
  # - ./git-ftp catchup -s $TRAVIS_BRANCH -v
  - 'FTP_URL="${!GIT_FTP_URL_BRANCH}" ./koi build -e local'
  # - git commit -m deploy --all
deploy:
  - provider: script
    script: ./git-ftp push -s $TRAVIS_BRANCH -v -f
    skip_cleanup: true
    on:
      all_branches: true
  # - provider: script
  #   script: ./git-ftp push -s $TRAVIS_BRANCH -v -f
  #   skip_cleanup: true
  #   on:
  #     branch: beta
