env:
  global:
    - PROJECT_NAME=bkt-bicipublica
    # master SHA256-606c78f9bd55e946b34762b7f54b65177eaa37a3fc42559ea62712cf30431b2b
    - secure: ""
    # beta SHA256-
    - secure: "Zm5gLfnNKoNamrX1fnaaLclVKlVptpP6+xH1M8xDo7LbfGpuy5NOwkf2s8iEsbOE71Bav/8wTIcqIEZldExrq2V24AywB09PyPlBoShudXyDYk2aF3OjmH/FC7vOb47UPjTyDRrD5VJAcPbrTL4AXF+cGjCJgbqWL10zeXdFADVSJB430ugF+et59SgwYnCQEjTNspkGN7xwH6/XiLL3rllo6ZUG4rZDIIhAAoZ9ZHVzgpkb3C7IzxwCMeV9AGolHzWnx5VTe8pqTsEuoSZen3crTd7XbIlvVJeJNRwBnpTqs/CLbRmK7Jx0XTJm1OVT/4YL4mN3Bo43S6WtSbdniNoujnXbiYdNjXmze8vqs/sguutxz21xj7UkduMXNWBkYMBvY4vnZAiKDstXibgHQIFmJI/Onaw6S3l8EJIo4BgWwo5lGZOAuaLSZNTyN1SjSCdDhvdSbaIbGUiXqjxrCJWDxLnfGE1+pdm3V9V4oaSAfEj065pAQifHCtfhKswELQuFxXm49VFV3r+cYv3kRz0GHFXGS18iBcY5iyeMNvQIhEfiHXs80a6w+KRe3bypXe399fItSd+0hTdSAMP2AVLkLTLZdKjHguRSaHS/+GaIULhCeRY3Ga5YAULKRgsXUdX36WBtmsEQ2b6dm0ysgv+S8HlIRSGCZwrp68eBxQ4="
script:
  - true
notifications:
  email: false
  slack: krrrunch:Heq9HQZoEZT9rZJohu8in30e
language: node_js
node_js:
  - "6"
before_deploy:
  - 'git config --global user.email "deploy@travis-ci"'
  - 'git config --global user.name "[Deploy]"'
  - export GIT_FTP_URL_BRANCH=GIT_FTP_URL_$TRAVIS_BRANCH
  - './git-ftp add-scope $TRAVIS_BRANCH "${!GIT_FTP_URL_BRANCH}"'
  - git config git-ftp.syncroot public
  - npm install -g uglify-js
  - gem install sass -v 3.4.23 --no-ri --no-rdoc
  # - ./git-ftp catchup -s $TRAVIS_BRANCH -v
  - 'FTP_URL="${!GIT_FTP_URL_BRANCH}" ./koi build -e local'
  # - git commit -m deploy --all
deploy:
  - provider: script
    script: ./git-ftp push -s $TRAVIS_BRANCH -v -f
    skip_cleanup: true
    on:
      branch: master
   - provider: script
    script: ./git-ftp push -s $TRAVIS_BRANCH -v -f
    skip_cleanup: true
    on:
      branch: beta
  # - provider: script
  #   script: ./git-ftp push -s $TRAVIS_BRANCH -v -f
  #   skip_cleanup: true
  #   on:
  #     branch: beta